# Generated by Django 4.0.6 on 2022-07-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematica_app', '0003_facturacionboleta_usuario_usuario_membrecia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
